import { supabase } from './supabase-config.js';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const loginView=$('#login-view'),dashboardView=$('#dashboard-view'),loginForm=$('#login-form'),logoutBtn=$('#logout-btn');
let caches={projects:[],experiences:[],contacts:[],expertise:[],publications:[],skills:[],education:[],profileItems:[],nav:[]};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const lines=v=>String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),csv=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const status=(el,text,type='')=>{if(!el)return;el.textContent=text||'';el.className=`form-status ${type}`.trim();};
const fmt=v=>v?new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'';
const slugify=s=>String(s||'project').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||`project-${Date.now()}`;
const scrollToForm=f=>f?.scrollIntoView({behavior:'smooth',block:'center'});
async function isAdmin(){const {data,error}=await supabase.rpc('is_admin');return !error&&data===true;}
async function showSession(session){if(!session){loginView.hidden=false;dashboardView.hidden=true;logoutBtn.hidden=true;return;}if(!(await isAdmin())){await supabase.auth.signOut();status($('#login-status'),'This account is not registered as an administrator.','error');return showSession(null);}loginView.hidden=true;dashboardView.hidden=false;logoutBtn.hidden=false;$('#admin-email').textContent=session.user.email||'';await Promise.all([loadSettings(),loadMessages(),loadProjects(),loadExperiences(),loadContacts(),loadExpertise(),loadPublications(),loadSkills(),loadEducation(),loadProfileItems(),loadNav()]);}
loginForm.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(loginForm);status($('#login-status'),'Signing in…');const {data,error}=await supabase.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});if(error)return status($('#login-status'),error.message,'error');status($('#login-status'),'');await showSession(data.session);});
logoutBtn.onclick=async()=>{await supabase.auth.signOut();await showSession(null);};
async function upload(bucket,file,prefix='file'){const ext=(file.name.split('.').pop()||'bin').toLowerCase(),path=`${prefix}/${Date.now()}-${Math.random().toString(36).slice(2,8)}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;}

async function loadSettings(){const {data,error}=await supabase.from('site_settings').select('*').eq('id',1).single();if(error)return status($('#settings-status'),error.message,'error');const f=$('#settings-form');Object.entries(data).forEach(([k,v])=>{const el=f.elements[k];if(!el)return;if(el.type==='checkbox')el.checked=!!v;else if(k==='about_paragraphs')el.value=(v||[]).join('\n\n');else el.value=v??'';});}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,fd=new FormData(form);status($('#settings-status'),'Saving…');let resumeUrl=String(fd.get('resume_url')||'').trim(),socialImage=String(fd.get('social_image_url')||'').trim();try{if(form.elements.resume_file.files[0])resumeUrl=await upload('site-files',form.elements.resume_file.files[0],'resume');if(form.elements.social_image_file.files[0])socialImage=await upload('site-files',form.elements.social_image_file.files[0],'social');}catch(err){return status($('#settings-status'),err.message,'error');}
 const bools=['show_resume','resume_download','show_about','show_expertise','show_experience','show_projects','show_publications','show_skills','show_education','show_contact','show_contact_form','show_additional'];
 const fields=['full_name','professional_title','hero_lead','portrait_line_1','portrait_line_2','about_heading','contact_heading','contact_lead','footer_text','seo_title','seo_description','resume_label','section_about_label','section_expertise_label','section_experience_label','section_projects_label','section_publications_label','section_skills_label','section_education_label','section_contact_label','section_additional_label'];
 const payload={id:1,about_paragraphs:String(fd.get('about_paragraphs')||'').split(/\n\s*\n|\r?\n/).map(x=>x.trim()).filter(Boolean),resume_url:resumeUrl,social_image_url:socialImage,updated_at:new Date().toISOString()};fields.forEach(k=>payload[k]=String(fd.get(k)||'').trim());bools.forEach(k=>payload[k]=!!form.elements[k]?.checked);
 const {error}=await supabase.from('site_settings').upsert(payload);if(error)return status($('#settings-status'),error.message,'error');form.elements.resume_url.value=resumeUrl;form.elements.social_image_url.value=socialImage;form.elements.resume_file.value='';form.elements.social_image_file.value='';status($('#settings-status'),'Saved. Refresh the public site to see the changes.','success');});

async function loadMessages(){const {data,error}=await supabase.from('messages').select('*').order('created_at',{ascending:false});const list=$('#messages-list');if(error){list.innerHTML=`<p class="empty-state">${esc(error.message)}</p>`;return;}$('#message-count').textContent=data.length;list.innerHTML=data.length?data.map(m=>`<article class="message-item ${m.is_read?'':'unread'}" data-id="${m.id}"><div class="message-meta"><span>${esc(m.name)}</span><span>${esc(m.email)}</span><span>${esc(fmt(m.created_at))}</span></div><h4>${esc(m.subject||'No subject')}</h4><p>${esc(m.message)}</p><div class="item-actions"><button data-act="read">Mark ${m.is_read?'unread':'read'}</button><a class="ghost-btn" href="mailto:${encodeURIComponent(m.email)}?subject=${encodeURIComponent('Re: '+(m.subject||'Your message'))}">Reply</a><button data-act="delete">Delete</button></div></article>`).join(''):'<p class="empty-state">No messages yet.</p>';$$('#messages-list [data-act="read"]').forEach(b=>b.onclick=async()=>{const r=b.closest('article'),unread=r.classList.contains('unread');await supabase.from('messages').update({is_read:unread}).eq('id',r.dataset.id);loadMessages();});$$('#messages-list [data-act="delete"]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this message?')){await supabase.from('messages').delete().eq('id',b.closest('article').dataset.id);loadMessages();}});}
$('#refresh-messages').onclick=loadMessages;

function listHTML(rows,subtitleFn,titleFn){return rows.length?rows.map(x=>`<article class="admin-project-item" data-id="${x.id}"><div class="project-admin-meta"><span>${x.published?'PUBLISHED':'DRAFT'}</span><span>ORDER ${esc(x.sort_order)}</span></div><h4>${esc(titleFn?titleFn(x):(x.title||x.role||x.label||x.degree||x.name))}</h4>${subtitleFn?`<p class="admin-item-subtitle">${esc(subtitleFn(x)||'')}</p>`:''}<div class="item-actions"><button data-act="edit">Edit</button><button data-act="toggle">${x.published?'Hide':'Show'}</button><button data-act="delete">Delete</button></div></article>`).join(''):'<p class="empty-state">No items yet.</p>';}
function clearForm(form){form.reset();if(form.elements.id)form.elements.id.value='';if(form.elements.sort_order)form.elements.sort_order.value=100;if(form.elements.published)form.elements.published.checked=true;}
function bindList(listSel,key,table,form,fill,load){const list=$(listSel);list.querySelectorAll('[data-act="edit"]').forEach(b=>b.onclick=()=>{const x=caches[key].find(r=>String(r.id)===b.closest('article').dataset.id);fill(x);scrollToForm(form);});list.querySelectorAll('[data-act="toggle"]').forEach(b=>b.onclick=async()=>{const x=caches[key].find(r=>String(r.id)===b.closest('article').dataset.id);await supabase.from(table).update({published:!x.published,updated_at:new Date().toISOString()}).eq('id',x.id);load();});list.querySelectorAll('[data-act="delete"]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this item?'))return;await supabase.from(table).delete().eq('id',b.closest('article').dataset.id);load();});}
function setupSimple({key,table,list,formSel,newBtn,subtitle,fields,countSel,titleFn}){const form=$(formSel);const fill=x=>Object.keys(x).forEach(k=>{const el=form.elements[k];if(!el)return;if(el.type==='checkbox')el.checked=!!x[k];else el.value=x[k]??'';});const load=async()=>{const {data,error}=await supabase.from(table).select('*').order('sort_order');if(error)return; caches[key]=data;if(countSel)$(countSel).textContent=data.length;$(list).innerHTML=listHTML(data,subtitle,titleFn);bindList(list,key,table,form,fill,load);};form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),id=fd.get('id'),payload={};fields.forEach(k=>{const el=form.elements[k];if(el.type==='checkbox')payload[k]=el.checked;else if(el.type==='number')payload[k]=fd.get(k)?Number(fd.get(k)):null;else payload[k]=String(fd.get(k)||'').trim();});payload.updated_at=new Date().toISOString();const {error}=id?await supabase.from(table).update(payload).eq('id',id):await supabase.from(table).insert(payload);if(error)return alert(error.message);clearForm(form);load();});$(newBtn).onclick=()=>{clearForm(form);scrollToForm(form);};form.querySelector('[data-clear]')?.addEventListener('click',()=>clearForm(form));return load;}

async function loadProjects(){const {data,error}=await supabase.from('projects').select('*').order('sort_order').order('created_at',{ascending:false});if(error)return;caches.projects=data;$('#project-count').textContent=data.length;$('#projects-list').innerHTML=listHTML(data,x=>[x.year,x.role,x.project_status].filter(Boolean).join(' · '));bindList('#projects-list','projects','projects',$('#project-form'),fillProject,loadProjects);}
function fillProject(x){const f=$('#project-form');for(const k of ['id','title','year','role','project_status','description','sort_order'])if(f.elements[k])f.elements[k].value=x[k]??'';f.elements.technologies.value=(x.technologies||[]).join(', ');f.elements.published.checked=!!x.published;$('#current-media').innerHTML=[x.cover_image,...(x.gallery||[])].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).map(u=>`<img src="${esc(u)}" alt="">`).join('');}
$('#project-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=fd.get('id');status($('#project-status'),'Saving…');const old=caches.projects.find(x=>String(x.id)===String(id));let cover=old?.cover_image||'',gallery=[...(old?.gallery||[])];try{if(f.elements.cover.files[0])cover=await upload('project-images',f.elements.cover.files[0],'covers');for(const file of f.elements.gallery.files)gallery.push(await upload('project-images',file,'gallery'));}catch(err){return status($('#project-status'),err.message,'error');}const payload={title:String(fd.get('title')).trim(),year:fd.get('year')?Number(fd.get('year')):null,role:String(fd.get('role')||'').trim(),project_status:String(fd.get('project_status')||'').trim(),description:String(fd.get('description')).trim(),technologies:csv(fd.get('technologies')),cover_image:cover,gallery:[...new Set(gallery.filter(Boolean))],published:f.elements.published.checked,sort_order:Number(fd.get('sort_order')||100),updated_at:new Date().toISOString()};const q=id?supabase.from('projects').update(payload).eq('id',id):supabase.from('projects').insert({...payload,slug:`${slugify(payload.title)}-${Date.now()}`});const {error}=await q;if(error)return status($('#project-status'),error.message,'error');clearForm(f);$('#current-media').innerHTML='';status($('#project-status'),'Saved.','success');loadProjects();});
$('#new-project-btn').onclick=()=>{clearForm($('#project-form'));scrollToForm($('#project-form'));};$('#cancel-edit-btn').onclick=()=>{clearForm($('#project-form'));$('#current-media').innerHTML='';};

async function loadExperiences(){const {data,error}=await supabase.from('experiences').select('*').order('sort_order');if(error)return;caches.experiences=data;$('#experience-count').textContent=data.length;$('#experiences-list').innerHTML=listHTML(data,x=>`${x.company} · ${x.period}`);bindList('#experiences-list','experiences','experiences',$('#experience-form'),fillExperience,loadExperiences);}
function fillExperience(x){const f=$('#experience-form');for(const k of ['id','role','company','period','summary','sort_order'])f.elements[k].value=x[k]??'';f.elements.responsibilities.value=(x.responsibilities||[]).join('\n');f.elements.published.checked=!!x.published;}
$('#experience-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=fd.get('id'),payload={role:String(fd.get('role')).trim(),company:String(fd.get('company')).trim(),period:String(fd.get('period')).trim(),summary:String(fd.get('summary')).trim(),responsibilities:lines(fd.get('responsibilities')),published:f.elements.published.checked,sort_order:Number(fd.get('sort_order')||100),updated_at:new Date().toISOString()};const {error}=id?await supabase.from('experiences').update(payload).eq('id',id):await supabase.from('experiences').insert(payload);if(error)return status($('#experience-status'),error.message,'error');clearForm(f);status($('#experience-status'),'Saved.','success');loadExperiences();});$('#new-experience-btn').onclick=()=>{clearForm($('#experience-form'));scrollToForm($('#experience-form'));};$('#cancel-experience-btn').onclick=()=>clearForm($('#experience-form'));

async function loadContacts(){const {data,error}=await supabase.from('contact_links').select('*').order('sort_order');if(error)return;caches.contacts=data;$('#contacts-list').innerHTML=listHTML(data,x=>x.value||x.platform);bindList('#contacts-list','contacts','contact_links',$('#contact-link-form'),fillContact,loadContacts);}
function fillContact(x){const f=$('#contact-link-form');for(const k of ['id','platform','label','value','url','icon','sort_order'])f.elements[k].value=x[k]??'';f.elements.published.checked=!!x.published;}
$('#contact-link-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=fd.get('id'),payload={platform:String(fd.get('platform')||'custom').trim(),label:String(fd.get('label')).trim(),value:String(fd.get('value')).trim(),url:String(fd.get('url')).trim(),icon:String(fd.get('icon')||'↗').trim(),published:f.elements.published.checked,sort_order:Number(fd.get('sort_order')||100),updated_at:new Date().toISOString()};const {error}=id?await supabase.from('contact_links').update(payload).eq('id',id):await supabase.from('contact_links').insert(payload);if(error)return status($('#contact-link-status'),error.message,'error');clearForm(f);status($('#contact-link-status'),'Saved.','success');loadContacts();});$('#new-contact-btn').onclick=()=>{clearForm($('#contact-link-form'));scrollToForm($('#contact-link-form'));};$('#clear-contact-btn').onclick=()=>clearForm($('#contact-link-form'));

const loadNav=setupSimple({key:'nav',table:'nav_items',list:'#nav-items-list',formSel:'#nav-item-form',newBtn:'#new-nav-btn',subtitle:x=>x.target,fields:['label','target','sort_order','published'],titleFn:x=>x.label});
const loadExpertise=setupSimple({key:'expertise',table:'expertise_items',list:'#expertise-admin-list',formSel:'#expertise-form',newBtn:'#new-expertise-btn',subtitle:x=>x.description,fields:['title','icon','description','sort_order','published']});
const loadPublications=setupSimple({key:'publications',table:'publications',list:'#publications-admin-list',formSel:'#publication-form',newBtn:'#new-publication-btn',subtitle:x=>`${x.journal} · ${x.status||''} · ${x.year||''}`,fields:['year','title','authors','status','journal','publisher','doi','publisher_url','sort_order','published'],countSel:'#publication-count'});
const loadSkills=setupSimple({key:'skills',table:'skills',list:'#skills-admin-list',formSel:'#skill-form',newBtn:'#new-skill-btn',subtitle:x=>`${x.category}${x.level?' · '+x.level:''}`,fields:['category','name','level','sort_order','published'],titleFn:x=>x.name});
const loadProfileItems=setupSimple({key:'profileItems',table:'profile_items',list:'#profile-items-admin-list',formSel:'#profile-item-form',newBtn:'#new-profile-item-btn',subtitle:x=>`${x.category}${x.subtitle?' · '+x.subtitle:''}`,fields:['category','title','subtitle','description','url','link_label','sort_order','published']});
const loadEducation=setupSimple({key:'education',table:'education_items',list:'#education-admin-list',formSel:'#education-form',newBtn:'#new-education-btn',subtitle:x=>`${x.institution} · ${x.period}`,fields:['period','degree','institution','sort_order','published']});
const {data:{session}}=await supabase.auth.getSession();await showSession(session);supabase.auth.onAuthStateChange((_event,session)=>{if(!session)showSession(null);});
