const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}})},{threshold:.08});document.querySelectorAll('.hero-copy,.portrait-area').forEach(e=>{e.classList.add('reveal');observer.observe(e)});

const lightbox=document.getElementById('lightbox');const lightboxImage=document.getElementById('lightbox-image');const counter=document.getElementById('lightbox-counter');const prevBtn=document.querySelector('.lightbox-prev');const nextBtn=document.querySelector('.lightbox-next');let gallery=[];let galleryIndex=0;let lastTrigger=null;
function showGalleryImage(){if(!gallery.length)return;lightboxImage.src=gallery[galleryIndex];counter.textContent=gallery.length>1?`${galleryIndex+1} / ${gallery.length}`:'PROJECT VIEW';prevBtn.style.display=gallery.length>1?'block':'none';nextBtn.style.display=gallery.length>1?'block':'none'}
function openCard(card){try{gallery=JSON.parse(card.dataset.gallery||'[]')}catch{gallery=[]}if(!gallery.length)return;lastTrigger=card;galleryIndex=0;showGalleryImage();lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.querySelector('.lightbox-close').focus()}
window.initializeProjectCards=function(){document.querySelectorAll('.project-card-image').forEach(card=>{if(card.dataset.bound)return;card.dataset.bound='1';card.addEventListener('click',()=>openCard(card));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openCard(card)}})})};
window.initializeProjectCards();
function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow='';lastTrigger?.focus?.()}
document.querySelector('.lightbox-close').addEventListener('click',closeLightbox);prevBtn.addEventListener('click',()=>{galleryIndex=(galleryIndex-1+gallery.length)%gallery.length;showGalleryImage()});nextBtn.addEventListener('click',()=>{galleryIndex=(galleryIndex+1)%gallery.length;showGalleryImage()});lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft'&&gallery.length>1){galleryIndex=(galleryIndex-1+gallery.length)%gallery.length;showGalleryImage()}if(e.key==='ArrowRight'&&gallery.length>1){galleryIndex=(galleryIndex+1)%gallery.length;showGalleryImage()}});
